export default {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'scope-enum': [
      2,
      'always',
      [
        'contracts',
        'core',
        'scanner',
        'laravel',
        'analyzer-routes',
        'analyzer-controllers',
        'analyzer-middleware',
        'analyzer-services',
        'analyzer-repositories',
        'analyzer-models',
        'analyzer-events',
        'analyzer-jobs',
        'analyzer-policies',
        'analyzer-schedule',
        'exporter-json',
        'exporter-mermaid',
        'ui',
        'desktop',
        'ci',
        'deps',
        'release',
        'docs',
        'repo',
      ],
    ],
    'scope-empty': [1, 'never'],
  },
};
