REPO="novaprime-code/codeatlas"

gh api repos/$REPO/milestones -f title="v0.0.1 — Foundation" -f description="Infrastructure, CI, tooling. Zero features." -f state="open"
gh api repos/$REPO/milestones -f title="v0.1.0 — First Light" -f description="Core, Contracts, Scanner, Route Analyzer, JSON Exporter, Basic Viewer"
gh api repos/$REPO/milestones -f title="v0.2.0 — Connections" -f description="Middleware Analyzer, Controller Analyzer"
gh api repos/$REPO/milestones -f title="v0.3.0 — Depth" -f description="Service Analyzer, Repository Analyzer"
gh api repos/$REPO/milestones -f title="v0.4.0 — Relationships" -f description="Model Analyzer, Database/Migration Analyzer"
gh api repos/$REPO/milestones -f title="v0.5.0 — Flow" -f description="Event Analyzer, Job Analyzer, Notification Analyzer"
gh api repos/$REPO/milestones -f title="v0.6.0 — Authority" -f description="Policy Analyzer, Schedule Analyzer, Cache Analyzer"
gh api repos/$REPO/milestones -f title="v0.7.0 — Big Picture" -f description="Full Dependency Graph, Architecture Dashboard"
gh api repos/$REPO/milestones -f title="v0.8.0 — Desktop" -f description="Tauri desktop application"
gh api repos/$REPO/milestones -f title="v0.9.0 — Editor" -f description="VS Code extension"
gh api repos/$REPO/milestones -f title="v1.0.0 — Atlas" -f description="Stable release, public API freeze"